In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_csv("cleaned_data.csv")

In [3]:
df

,Unnamed: 0,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,...,{'0': '20'},"{'0': 'Adult-18+', '1': 'Adult-18+', '2': 'Adu...","{'0': 'Male', '1': 'Male', '3': 'Male', '4': '...",{'0': 'Julian-Sims'},{},"{'0': 'Arrested', '1': 'Injured', '2': 'Injure...","{'0': 'Victim', '1': 'Victim', '2': 'Victim', ...",http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,...,{'0': '20'},"{'0': 'Adult-18+', '1': 'Adult-18+', '2': 'Adu...",{'0': 'Male'},{'0': 'Bernard-Gillis'},{},"{'0': 'Killed', '1': 'Injured', '2': 'Injured'...","{'0': 'Victim', '1': 'Victim', '2': 'Victim', ...",http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,...,"{'0': '25', '1': '31', '2': '33', '3': '34', '...","{'0': 'Adult-18+', '1': 'Adult-18+', '2': 'Adu...","{'0': 'Male', '1': 'Male', '2': 'Male', '3': '...","{'0': 'Damien-Bell', '1': 'Desmen-Noble', '2':...",{},"{'0': 'Injured,-Unharmed,-Arrested', '1': 'Unh...","{'0': 'Subject-Suspect', '1': 'Subject-Suspect...",http://www.morningjournal.com/general-news/201...,56.0,13.0
3,3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,...,"{'0': '29', '1': '33', '2': '56', '3': '33'}","{'0': 'Adult-18+', '1': 'Adult-18+', '2': 'Adu...","{'0': 'Female', '1': 'Male', '2': 'Male', '3':...","{'0': 'Stacie-Philbrook', '1': 'Christopher-Ra...",{},"{'0': 'Killed', '1': 'Killed', '2': 'Killed', ...","{'0': 'Victim', '1': 'Victim', '2': 'Victim', ...",http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,...,"{'0': '18', '1': '46', '2': '14', '3': '47'}","{'0': 'Adult-18+', '1': 'Adult-18+', '2': 'Tee...","{'0': 'Female', '1': 'Male', '2': 'Male', '3':...","{'0': 'Danielle-Imani-Jameison', '1': 'Maurice...",{'3': 'Family'},"{'0': 'Injured', '1': 'Injured', '2': 'Killed'...","{'0': 'Victim', '1': 'Victim', '2': 'Victim', ...",http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,239672,1083142,2018-03-31,Louisiana,Rayne,North Riceland Road and Highway 90,0,0,http://www.gunviolencearchive.org/incident/108...,http://www.klfy.com/news/local/rayne-woman-cha...,...,{'0': '25'},{'0': 'Adult-18+'},{'0': 'Female'},{'0': 'Jhkeya-Tezeno'},{},"{'0': 'Unharmed,-Arrested'}",{'0': 'Subject-Suspect'},http://www.klfy.com/news/local/rayne-woman-cha...,NaN,NaN
239673,239673,1083139,2018-03-31,Louisiana,Natchitoches,247 Keyser Ave,1,0,http://www.gunviolencearchive.org/incident/108...,http://www.ksla.com/story/37854648/man-wanted-...,...,{'1': '21'},"{'0': 'Adult-18+', '1': 'Adult-18+'}","{'0': 'Male', '1': 'Male'}","{'0': 'Jamal-Haskett', '1': 'Jaquarious-Tyjuan...",{},"{'0': 'Killed', '1': 'Unharmed,-Arrested'}","{'0': 'Victim', '1': 'Subject-Suspect'}",http://www.ksla.com/story/37854648/man-wanted-...,23.0,31.0
239674,239674,1083151,2018-03-31,Louisiana,Gretna,1300 block of Cook Street,0,1,http://www.gunviolencearchive.org/incident/108...,http://www.nola.com/crime/index.ssf/2018/04/sh...,...,{'0': '21'},{'0': 'Adult-18+'},{'0': 'Male'},{},{},{'0': 'Injured'},{'0': 'Victim'},http://www.nola.com/crime/index.ssf/2018/04/sh...,85.0,7.0
239675,239675,1082514,2018-03-31,Texas,Houston,12630 Ashford Point Dr,1,0,http://www.gunviolencearchive.org/incident/108...,https://www.chron.com/news/houston-texas/houst...,...,{'0': '42'},{'0': 'Adult-18+'},{'0': 'Male'},{'0': 'Leroy-Ellis'},{},{'0': 'Killed'},{'0': 'Victim'},http://www.khou.com/article/news/hpd-investiga...,149.0,17.0
239676,239676,1081940,2018-03-31,Maine,Norridgewock,434 Skowhegan Rd,2,0,http://www.gunviolencearchive.org/incident/108...,https://www.centralmaine.com/2018/03/31/police...,...,"{'0': '58', '1': '62'}","{'0': 'Adult-18+', '1': 'Adult-18+'}","{'0': 'Female', '1': 'Male'}","{'0': 'Marie-Lancaster-Hale', '1': 'William-Ha...",{'1': 'Significant-others---current-or-former'},"{'0': 'Killed', '1': 'Killed'}","{'0': 'Victim', '1': 'Subject-Suspect'}",https://www.centralmaine.com/2018/03/31/police...,111.0,3.0

# Incidents Table

In [4]:
data = {
    'incident_id': df['incident_id'],
    'date': df['date'],
    'state': df['state'],
    'city_or_county': df['city_or_county'],
    'address': df['address'],
    'n_killed': df['n_killed'],
    'n_injured': df['n_injured'],
    'incident_url': df['incident_url'],
    'source_url': df['source_url'],
    'congressional_district': df['congressional_district'],
    'incident_characteristics': df['incident_characteristics'],
    'latitude': df['latitude'],
    'location_description': df['location_description'],
    'longitude': df['longitude'],
    'n_guns_involved': df['n_guns_involved'],
    'notes': df['notes'],
    'sources': df['sources'],
    'state_house_district': df['state_house_district'],
    'state_senate_district': df['state_senate_district']
}

incidents = pd.DataFrame(data)

In [5]:
incidents

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,congressional_district,incident_characteristics,latitude,location_description,longitude,n_guns_involved,notes,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,14.0,"['Shot---Wounded/Injured', 'Mass-Shooting-(4+-...",40.3467,NaN,-79.8559,NaN,Julian Sims under investigation: Four Shot and...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,43.0,"['Shot---Wounded/Injured', 'Shot---Dead-(murde...",33.9090,NaN,-118.3330,NaN,Four Shot; One Killed; Unidentified shooter in...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,9.0,"['Shot---Wounded/Injured', 'Shot---Dead-(murde...",41.4455,Cotton Club,-82.1377,2.0,NaN,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,6.0,"['Shot---Dead-(murder,-accidental,-suicide)', ...",39.6518,NaN,-104.8020,NaN,NaN,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,6.0,"['Shot---Wounded/Injured', 'Shot---Dead-(murde...",36.1140,NaN,-79.9569,2.0,Two firearms recovered. (Attempted) murder sui...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,2018-03-31,Louisiana,Rayne,North Riceland Road and Highway 90,0,0,http://www.gunviolencearchive.org/incident/108...,http://www.klfy.com/news/local/rayne-woman-cha...,NaN,['Shots-Fired---No-Injuries'],NaN,NaN,NaN,1.0,NaN,http://www.klfy.com/news/local/rayne-woman-cha...,NaN,NaN
239673,1083139,2018-03-31,Louisiana,Natchitoches,247 Keyser Ave,1,0,http://www.gunviolencearchive.org/incident/108...,http://www.ksla.com/story/37854648/man-wanted-...,4.0,"['Shot---Dead-(murder,-accidental,-suicide)', ...",31.7537,Shop Rite,-93.0836,1.0,NaN,http://www.ksla.com/story/37854648/man-wanted-...,23.0,31.0
239674,1083151,2018-03-31,Louisiana,Gretna,1300 block of Cook Street,0,1,http://www.gunviolencearchive.org/incident/108...,http://www.nola.com/crime/index.ssf/2018/04/sh...,2.0,['Shot---Wounded/Injured'],29.9239,NaN,-90.0442,1.0,NaN,http://www.nola.com/crime/index.ssf/2018/04/sh...,85.0,7.0
239675,1082514,2018-03-31,Texas,Houston,12630 Ashford Point Dr,1,0,http://www.gunviolencearchive.org/incident/108...,https://www.chron.com/news/houston-texas/houst...,9.0,"['Shot---Dead-(murder,-accidental,-suicide)']",29.7201,Vanderbilt Court apartments,-95.6110,1.0,"Vic was found shot to death in car on 4/1/18, ...",http://www.khou.com/article/news/hpd-investiga...,149.0,17.0
239676,1081940,2018-03-31,Maine,Norridgewock,434 Skowhegan Rd,2,0,http://www.gunviolencearchive.org/incident/108...,https://www.centralmaine.com/2018/03/31/police...,2.0,"['Shot---Dead-(murder,-accidental,-suicide)', ...",44.7293,NaN,-69.7691,2.0,"ALT: US 2, shot wife then self, handgun, shotg...",https://www.centralmaine.com/2018/03/31/police...,111.0,3.0

# Gun Table

In [6]:
df2 = df[df['n_guns_involved']>0].reset_index()
gun_id = []
incident_id = []

In [7]:
for i in range(len(df2)):
    for j in range(int(df2.loc[i]['n_guns_involved'])):
        incident_id_i = str(df2.loc[i]['incident_id'])
        index_id = str(j)
        gun_id.append(incident_id_i + index_id)
        incident_id.append(incident_id_i)

In [8]:
gun_stolen = [0] * len(gun_id)
gun_type = [0] * len(gun_id)
counter = 0

In [9]:
for i in range(len(df2)):
    for j in range(int(df2.loc[i]['n_guns_involved'])):
        index_id = str(j)
            
        stolen_keys = list(json.loads(df2['gun_stolen'].loc[i].replace("\'", "\"")).keys())
        type_keys = list(json.loads(df2['gun_type'].loc[i].replace("\'", "\"")).keys())
        
        if index_id in stolen_keys:
            stolen = json.loads(df2['gun_stolen'].loc[i].replace("\'", "\""))[index_id]
            gun_stolen[counter] = stolen
            
        if index_id in type_keys:
            g_type = json.loads(df2['gun_type'].loc[i].replace("\'", "\""))[index_id]
            gun_type[counter] = g_type      
            
        counter += 1

In [10]:
data = {
    'gun_id': gun_id,
    'incident_id': incident_id,
    'stolen': gun_stolen,
    'type': gun_type
}

guns = pd.DataFrame(data)

In [11]:
guns

          gun_id incident_id   stolen     type
0        4788550      478855  Unknown  Unknown
1        4788551      478855  Unknown  Unknown
2        4789590      478959  Unknown  Handgun
3        4789591      478959  Unknown  Handgun
4        4793630      479363  Unknown    22-LR
...          ...         ...      ...      ...
192447  10831390     1083139  Unknown  Unknown
192448  10831510     1083151  Unknown  Unknown
192449  10825140     1082514  Unknown  Unknown
192450  10819400     1081940  Unknown  Handgun
192451  10819401     1081940  Unknown  Shotgun

[192452 rows x 4 columns]

# Participant Table

In [12]:
df3 = df[df['participant_type']!='{}'].reset_index()
participant_id = []
incident_id = []

In [13]:
for i in range(len(df3)):
    for j in list(json.loads(df3['participant_type'].loc[i].replace("\'", "\"")).keys()):
        incident_id_i = str(df3.loc[i]['incident_id'])
        index_id = str(j)
        participant_id.append(incident_id_i + index_id)
        incident_id.append(incident_id_i)

In [14]:
part_age = [0] * len(participant_id)
part_age_group = [0] * len(participant_id)
part_gender = [0] * len(participant_id)
part_relationship = [0] * len(participant_id)
part_status = [0] * len(participant_id)
part_type = [0] * len(participant_id)
counter = 0

In [15]:
for i in range(len(df3)):
    for j in list(json.loads(df3['participant_type'].loc[i].replace("\'", "\"")).keys()):
        index_id = str(j)
            
        age_keys = list(json.loads(df3['participant_age'].loc[i].replace("\'", "\"")).keys())
        age_group_keys = list(json.loads(df3['participant_age_group'].loc[i].replace("\'", "\"")).keys())
        gender_keys = list(json.loads(df3['participant_gender'].loc[i].replace("\'", "\"")).keys())
        relationship_keys = list(json.loads(df3['participant_relationship'].loc[i].replace("\'", "\"")).keys())
        status_keys = list(json.loads(df3['participant_status'].loc[i].replace("\'", "\"")).keys())
        type_keys = list(json.loads(df3['participant_type'].loc[i].replace("\'", "\"")).keys())
        
        if index_id in age_keys:
            age = json.loads(df3['participant_age'].loc[i].replace("\'", "\""))[index_id]
            part_age[counter] = age
            
        if index_id in age_group_keys:
            age_group = json.loads(df3['participant_age_group'].loc[i].replace("\'", "\""))[index_id]
            part_age_group[counter] = age_group     
            
        if index_id in gender_keys:
            gender = json.loads(df3['participant_gender'].loc[i].replace("\'", "\""))[index_id]
            part_gender[counter] = gender   
            
        if index_id in relationship_keys:
            relationship = json.loads(df3['participant_relationship'].loc[i].replace("\'", "\""))[index_id]
            part_relationship[counter] = relationship
            
        if index_id in status_keys:
            status = json.loads(df3['participant_status'].loc[i].replace("\'", "\""))[index_id]
            part_status[counter] = status
            
        if index_id in type_keys:
            p_type = json.loads(df3['participant_type'].loc[i].replace("\'", "\""))[index_id]
            part_type[counter] = p_type 
        
        counter += 1

In [16]:
data = {
    'participant_id': participant_id,
    'incident_id': incident_id,
    'age': part_age,
    'age_group': part_age_group,
    'gender': part_gender,
    'relationship': part_relationship,
    'status': part_status,
    'type': part_type
}

participants = pd.DataFrame(data)

In [17]:
participants

,participant_id,incident_id,age,age_group,gender,relationship,status,type
0,4611050,461105,20,Adult-18+,Male,0,Arrested,Victim
1,4611051,461105,0,Adult-18+,Male,0,Injured,Victim
2,4611052,461105,0,Adult-18+,0,0,Injured,Victim
3,4611053,461105,0,Adult-18+,Male,0,Injured,Victim
4,4611054,461105,0,Adult-18+,Female,0,Injured,Subject-Suspect
...,...,...,...,...,...,...,...,...
385508,10831391,1083139,21,Adult-18+,Male,0,"Unharmed,-Arrested",Subject-Suspect
385509,10831510,1083151,21,Adult-18+,Male,0,Injured,Victim
385510,10825140,1082514,42,Adult-18+,Male,0,Killed,Victim
385511,10819400,1081940,58,Adult-18+,Female,0,Killed,Victim
385512,10819401,1081940,62,Adult-18+,Male,Significant-others---current-or-former,Killed,Subject-Suspect

In [18]:
incidents.to_csv('incidents.csv')
participants.to_csv('participants.csv')
guns.to_csv('guns.csv')